services:
  - type: web
    name: bitspark-recommendation-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitspark-db
          property: connectionString
      - key: API_SECRET_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
    healthCheckPath: /health
    
databases:
  - name: bitspark-db
    databaseName: bitspark
    user: bitspark_user