services:
  - type: web
    name: bitspark-recommendation-engine
    env: python
    runtime: python-3.11.0
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --log-level info
    plan: free
    region: singapore
    branch: main
    rootDir: recommendation-engine
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: bitspark-db
          property: connectionString
      - key: API_SECRET_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
    healthCheckPath: /health
    
databases:
  - name: bitspark-db
    databaseName: bitspark
    user: bitspark_user